config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pins do
    member do
      put 'like', to: 'pins#upvote'
    end
  end

  root to: "pins#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
  belongs_to :user
  acts_as_votable

  has_attached_file :image, :styles => { :medium => "300x300>" }  
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
		@pin = current_user.pins.build
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
		@pin = current_user.pins.build(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @pin.upvote_by(current_user)
    
    redirect_to :back
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:title, :description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-dark bg-inverse navbar-fixed-top">
  <%= link_to "Puppy Reviews", root_path, class: "navbar-brand" %>
  <ul class="nav navbar-nav">

    <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to "New Pin", new_pin_path, class: 'nav-link' %>
      </li>

      <li class="nav-item">
		<%= link_to "Account", edit_user_registration_path, class: 'nav-link' %>
      </li>

      <li class="nav-item">
		<%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'nav-link' %>
      </li>	  
    <% else %>
	    <li class="nav-item">
			<%= link_to "Sign Up", new_user_registration_path, class: 'nav-link' %>	
	    </li>

	    <li class="nav-item">
			<%= link_to "Sign In", new_user_session_path, class: 'nav-link' %>
	    </li>
    <% end %>
		
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pini</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: "alert alert-info" %>
	<% end %>
	

	  <%= yield %>
  </div>
</body>

</html>

app/views/pins/_form.html.erb
<div class='card'>
  <div class='card-block'>
    <%= form_for(pin, html: { multipart: true }) do |f| %>
    <% if pin.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

        <ul>
        <% pin.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

	 <div class="form-group row"> 
	  <%= f.label :title, class: 'col-sm-2 form-control-label' %>
	  <div class='col-sm-7'>	 
	     <%= f.text_field :title, class: 'form-control' %>
	   </div>
	 </div>

	 <div class="form-group row">
	   <%= f.label :description, class: 'col-sm-2 form-control-label' %>
	   <div class='col-sm-7'>
	     <%= f.text_area :description, class: 'form-control' %>		   
	   </div>
	 </div>
	 	 
	 <div class='form-group row'>
		 &nbsp;&nbsp;
		<label class='col-sm-offset-2 file'>
		  <%= f.file_field :image %>	
		  <span class="file-custom"></span>
		</label>			 
	 </div>
  
	 <div class="form-group row">
	   <div class="col-sm-offset-2 col-sm-10">
	     <%= f.submit 'Submit', class: 'btn btn-primary' %>
	     <%= link_to 'Back', pins_path, class: 'btn btn-secondary' %>		  
	   </div>
	 </div>
  
    <% end %>
  </div>
</div>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>

<%= render 'form', pin: @pin %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<div class="transitions-enabled" id="pins">
  <% @pins.each do |pin| %>
    <div class="box card">
      <%= link_to (image_tag pin.image.url), pin %>
      <h2>
        <%= link_to pin.title, pin %>
      </h2>
      <p class="user">
        Submitted by
        <%= pin.user.email %>
      </p>
    </div>	
  <% end %>	
</div>	

<%= link_to 'New Pin', new_pin_path, class: 'btn btn-primary' %>

app/views/pins/new.html.erb
<h1>New Pin</h1>

<%= render 'form', pin: @pin %>

app/views/pins/show.html.erb
<div class="row" id="pin_show">
  <div class="col-lg-8 col-md-offset-2">
    <div class="card panel-default">
      <div class="card-header pin_image">
        <%= image_tag @pin.image.url %>
      </div>
      <div class="card-block">
        <h1>
          <%= @pin.title %>
        </h1>
        <p class="description">
          <%= @pin.description %>
        </p>
      </div>
      <div class="card-footer">
        <div class="row">
          <div class="col-lg-6">
            <p class="user">
              Submitted by
              <%= @pin.user.email %>
            </p>
          </div>
          <div class="col-lg-6">
            <div class="btn-group pull-right">
			    <%= link_to like_pin_path(@pin), method: :put, class: "btn btn-secondary" do %>
			      <i class="fa fa-heart"></i>
			      <%= @pin.get_upvotes.size %>
			    <% end %>
              <% if user_signed_in? %>
                <%= link_to "Edit", edit_pin_path, class: "btn btn-secondary" %>
                <%= link_to "Delete", pin_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-secondary" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>